version: "3.0"
# :name: only works in docker compose v2 https://www.docker.com/blog/announcing-compose-v2-general-availability/
# comment out if you don't want to activate compose v2
services:
  crypto-bot1:
    image: crypto-bot:local
    restart: always
    build: .
    environment:
      - PAIR=
      - CANDLE_INTERVAL=
      - SMA_FASTER_WINDOW=
      - SMA_SLOWER_WINDOW=
      - SMA_BOX_TOLERANCE=
    env_file:
      - .env
